"use client";

import { useCallback, useEffect, useState } from "react";
import { ReactFlow, Background, Controls, MiniMap, useNodesState, useEdgesState, type Node, type Edge, BackgroundVariant } from "@xyflow/react";
import { Check, ChevronLeft, ChevronRight, Copy, CopyPlus, Download, Eraser, ExternalLink, Folder, FolderPlus, GitBranchPlus, ImagePlus, LoaderCircle, Pencil, Plus, Save, Trash2, X, ZoomIn } from "lucide-react";
import "@xyflow/react/dist/style.css";
import PromptNode, { type PromptNodeData } from "@/components/PromptNode";

type PromptRow={id:number;workspace:string;project_name:string;content:string;version:number;iteration:number;input_images:string[];output_images:string[];created_at:string;updated_at:string};
type ProjectRow={id:number;name:string;prompt_count:number;created_at:string;updated_at:string};
type DraftMode="new"|"version"|"iteration";
const nodeTypes={promptNode:PromptNode};

function buildFlow(prompts:PromptRow[]):{nodes:Node[];edges:Edge[]} {
  const nodes:Node[]=[]; const edges:Edge[]=[]; const groups=new Map<string,PromptRow[]>();
  for(const p of prompts){const list=groups.get(p.project_name)||[];list.push(p);groups.set(p.project_name,list);}
  let offsetY=90;
  for(const [,rows] of groups){
    rows.sort((a,b)=>a.version-b.version||a.iteration-b.iteration);
    for(const r of rows) nodes.push({id:String(r.id),type:"promptNode",position:{x:110+(r.version-1)*310,y:offsetY+(r.iteration-1)*190},data:r as unknown as PromptNodeData});
    for(const r of rows){
      const next=rows.find(o=>o.version===r.version&&o.iteration===r.iteration+1);
      if(next) edges.push({id:`v-${r.id}-${next.id}`,source:String(r.id),target:String(next.id),type:"smoothstep",style:{stroke:"#90978b",strokeWidth:1.5}});
      const nextVer=rows.find(o=>o.version===r.version+1&&o.iteration===r.iteration);
      if(nextVer) edges.push({id:`h-${r.id}-${nextVer.id}`,source:String(r.id),target:String(nextVer.id),type:"smoothstep",style:{stroke:"#b6b9b1",strokeWidth:1,strokeDasharray:"5 4"}});
    }
    offsetY+=Math.max(320,rows.length*190+70);
  }
  return {nodes,edges};
}

type WorkspaceProps={workspace?:string;title?:string;studioLabel?:string;referenceMode?:"none"|"single"|"multi";embeddedInImageStudio?:boolean;outputLabel?:string;assetKind?:"image"|"media"};
const isVideoUrl=(url:string)=>/\.(mp4|webm|mov)(?:$|\?)/i.test(url);

export function PromptFlowWorkspace({workspace="text-to-image",title="文生图提示词",studioLabel="Image studio",referenceMode="none",embeddedInImageStudio=true,outputLabel="Output 图片",assetKind="image"}:WorkspaceProps){
  const [prompts,setPrompts]=useState<PromptRow[]>([]); const [projects,setProjects]=useState<ProjectRow[]>([]); const [nodes,setNodes,onNodesChange]=useNodesState<Node>([]); const [edges,setEdges,onEdgesChange]=useEdgesState<Edge>([]);
  const [selected,setSelected]=useState<PromptRow|null>(null); const [selectedProject,setSelectedProject]=useState<string|null>(null); const [projectNavCollapsed,setProjectNavCollapsed]=useState(false);
  const [draftMode,setDraftMode]=useState<DraftMode>("new"); const [draftSource,setDraftSource]=useState<PromptRow|null>(null);
  const [creatingProject,setCreatingProject]=useState(false); const [newProjectName,setNewProjectName]=useState(""); const [projectError,setProjectError]=useState("");
  const [editingProject,setEditingProject]=useState<ProjectRow|null>(null); const [editProjectName,setEditProjectName]=useState("");
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [saved,setSaved]=useState(false); const [uploading,setUploading]=useState(false);
  const [notice,setNotice]=useState<{type:"success"|"error";text:string}|null>(null); const [previewImage,setPreviewImage]=useState<string|null>(null);
  const [form,setForm]=useState({workspace,project_name:"",content:"",version:1,iteration:1,input_images:[] as string[],output_images:[] as string[]});
  const loadData=useCallback(async()=>{try{const query=encodeURIComponent(workspace);const [promptRes,projectRes]=await Promise.all([fetch(`/api/prompts?workspace=${query}`),fetch(`/api/projects?workspace=${query}`)]);const [promptJson,projectJson]=await Promise.all([promptRes.json(),projectRes.json()]);if(!promptRes.ok||!projectRes.ok)throw new Error("数据加载失败");setPrompts(promptJson.data||[]);setProjects(projectJson.data||[]);}catch(error){setNotice({type:"error",text:error instanceof Error?error.message:"数据加载失败"});}finally{setLoading(false);}},[workspace]);
  useEffect(()=>{loadData();},[loadData]);
  useEffect(()=>{setProjectNavCollapsed(localStorage.getItem("myprompt-project-nav-collapsed")==="true");},[]);
  useEffect(()=>{const visible=selectedProject?prompts.filter(p=>p.project_name===selectedProject):prompts;const flow=buildFlow(visible);setNodes(flow.nodes);setEdges(flow.edges);},[prompts,selectedProject,setNodes,setEdges]);
  const onNodeClick=useCallback((_:React.MouseEvent,node:Node)=>{const found=prompts.find(p=>String(p.id)===node.id);if(found){setSelected(found);setDraftMode("new");setDraftSource(null);setForm({workspace,project_name:found.project_name,content:found.content,version:found.version,iteration:found.iteration,input_images:found.input_images||[],output_images:found.output_images||[]});}},[prompts,workspace]);
  function resetForm(project=selectedProject||""){setDraftMode("new");setDraftSource(null);setForm({workspace,project_name:project,content:"",version:1,iteration:1,input_images:[],output_images:[]});setSelected(null);setNodes(ns=>ns.map(n=>({...n,selected:false})));}
  async function runSave(action:()=>Promise<Response>,successText:string){setSaving(true);setSaved(false);try{const res=await action();const json=await res.json();if(!res.ok)throw new Error(json.error||"操作失败");setSaved(true);setNotice({type:"success",text:successText});await loadData();setTimeout(()=>setSaved(false),1600);return res;}catch(error){setNotice({type:"error",text:error instanceof Error?error.message:"操作失败"});return null;}finally{setSaving(false);}}
  async function handleCreate(){if(!form.project_name.trim()){setNotice({type:"error",text:"请先选择项目"});return;}const res=await runSave(()=>fetch("/api/prompts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),draftMode==="version"?"新版本已保存":draftMode==="iteration"?"新迭代已保存":"提示词已创建");if(res)resetForm();}
  async function handleUpdate(){if(!selected)return;await runSave(()=>fetch(`/api/prompts/${selected.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),"提示词已更新");}
  async function handleDelete(){if(!selected||!confirm(`确认删除 ${selected.project_name} v${selected.version} / #${selected.iteration}？所属 Output 图片也会删除。`))return;const res=await fetch(`/api/prompts/${selected.id}`,{method:"DELETE"});if(!res.ok){const json=await res.json();setNotice({type:"error",text:json.error||"删除失败"});return;}setNotice({type:"success",text:"提示词已删除"});resetForm();await loadData();}
  function handleNewVersion(){if(!selected)return;setDraftSource(selected);setDraftMode("version");setForm({workspace,project_name:selected.project_name,content:selected.content,version:selected.version+1,iteration:1,input_images:selected.input_images||[],output_images:[]});setSelected(null);}
  function handleNewIteration(){if(!selected)return;setDraftSource(selected);setDraftMode("iteration");setForm({workspace,project_name:selected.project_name,content:selected.content,version:selected.version,iteration:selected.iteration+1,input_images:selected.input_images||[],output_images:[]});setSelected(null);}
  function discardDraft(){if(draftSource){setSelected(draftSource);setForm({workspace,project_name:draftSource.project_name,content:draftSource.content,version:draftSource.version,iteration:draftSource.iteration,input_images:draftSource.input_images||[],output_images:draftSource.output_images||[]});setDraftMode("new");setDraftSource(null);}else resetForm();}
  async function removeImage(url:string,index:number,field:"input_images"|"output_images"="output_images"){setForm(f=>({...f,[field]:f[field].filter((_,i)=>i!==index)}));if(!selected?.[field].includes(url)){await fetch(url,{method:"DELETE"});}else setNotice({type:"success",text:"素材已移除，保存修改后生效"});}
  async function handleUpload(file:File,field:"input_images"|"output_images"="output_images"){setUploading(true);const data=new FormData();data.append("file",file);const res=await fetch("/api/uploads",{method:"POST",body:data});const json=await res.json();if(res.ok)setForm(f=>({...f,[field]:referenceMode==="single"&&field==="input_images"?[json.data.url]:[...f[field],json.data.url]}));else setNotice({type:"error",text:json.error||"上传失败"});setUploading(false);}
  async function handleCreateProject(){const name=newProjectName.trim();if(!name)return setProjectError("请输入项目名称");const res=await fetch("/api/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name})});const json=await res.json();if(!res.ok)return setProjectError(json.error||"创建失败");await loadData();setSelectedProject(name);resetForm(name);setCreatingProject(false);setNewProjectName("");setProjectError("");}
  async function handleRenameProject(){if(!editingProject)return;const name=editProjectName.trim();if(!name)return setProjectError("请输入项目名称");const oldName=editingProject.name;const res=await fetch(`/api/projects/${editingProject.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name})});const json=await res.json();if(!res.ok)return setProjectError(json.error||"重命名失败");if(selectedProject===oldName)setSelectedProject(name);if(form.project_name===oldName)setForm(f=>({...f,project_name:name}));setEditingProject(null);setEditProjectName("");setProjectError("");setNotice({type:"success",text:"项目已重命名"});await loadData();}
  async function handleDeleteProject(project:ProjectRow){if(!confirm(`确认删除项目“${project.name}”？项目内 ${project.prompt_count} 条提示词和所属图片将一并删除。`))return;const res=await fetch(`/api/projects/${project.id}?cascade=true`,{method:"DELETE"});const json=await res.json();if(!res.ok)return setNotice({type:"error",text:json.error||"删除失败"});if(selectedProject===project.name){setSelectedProject(null);resetForm("");}setNotice({type:"success",text:"项目已删除"});await loadData();}
  const projectCount=projects.length;
  const visiblePromptCount=selectedProject?prompts.filter(p=>p.project_name===selectedProject).length:prompts.length;
  function toggleProjectNav(){setProjectNavCollapsed(value=>{const next=!value;localStorage.setItem("myprompt-project-nav-collapsed",String(next));return next;});}

  return <div className="relative flex h-full max-[760px]:pl-0" style={{paddingLeft:embeddedInImageStudio?"var(--image-sidebar-width)":0}}>
    {notice&&<div className={`absolute left-1/2 top-4 z-[80] flex -translate-x-1/2 items-center gap-2 rounded border px-3 py-2 text-xs shadow-md ${notice.type==="error"?"border-[#e4b9b6] bg-[#fff5f4] text-danger":"border-[#bac8b4] bg-[#f4f8f2] text-[#4f6548]"}`}>{notice.type==="error"?<X size={14}/>:<Check size={14}/>}<span>{notice.text}</span><button onClick={()=>setNotice(null)} title="关闭提示" className="ml-2 grid h-5 w-5 place-items-center border-0 bg-transparent opacity-60"><X size={11}/></button></div>}
    <aside className={`relative z-30 flex h-full shrink-0 flex-col border-r border-border bg-[#f7f7f4] transition-[width] max-[760px]:hidden ${projectNavCollapsed?"w-[48px]":"w-[190px]"}`}>
      <div className="flex h-[68px] items-center justify-between border-b border-border px-3">{!projectNavCollapsed&&<div><span className="text-[9px] font-semibold uppercase text-subtle">Projects</span><h2 className="mt-1 text-xs font-semibold">项目导航</h2></div>}<button onClick={toggleProjectNav} title={projectNavCollapsed?"展开项目导航":"收起项目导航"} className="grid h-8 w-8 place-items-center rounded border border-border bg-white text-muted hover:bg-accent-subtle">{projectNavCollapsed?<ChevronRight size={15}/>:<ChevronLeft size={15}/>}</button></div>
      {!projectNavCollapsed&&<>
        {creatingProject?<div className="m-2 rounded border border-[#b9c5b3] bg-white p-3 shadow-sm"><div className="flex items-center justify-between"><label className="text-[10px] font-semibold text-foreground">创建新项目</label><button onClick={()=>{setCreatingProject(false);setNewProjectName("");setProjectError("");}} title="放弃新项目" className="grid h-6 w-6 place-items-center rounded border-0 bg-transparent text-muted hover:bg-accent-subtle"><X size={13}/></button></div><input autoFocus value={newProjectName} onChange={e=>{setNewProjectName(e.target.value);setProjectError("");}} onKeyDown={e=>{if(e.key==="Enter")handleCreateProject();if(e.key==="Escape"){setCreatingProject(false);setNewProjectName("");setProjectError("");}}} placeholder="输入项目名称" className="mt-2 h-9 w-full rounded border border-border px-2.5 text-[11px] outline-none focus:border-[#6b7f63]"/>{projectError&&<p className="mt-1.5 text-[9px] text-danger">{projectError}</p>}<div className="mt-2 grid grid-cols-2 gap-2"><button onClick={()=>{setCreatingProject(false);setNewProjectName("");setProjectError("");}} className="flex h-9 items-center justify-center gap-1.5 rounded border border-border bg-white text-[10px] font-medium text-muted"><X size={12}/>放弃</button><button onClick={handleCreateProject} className="flex h-9 items-center justify-center gap-1.5 rounded border-0 bg-accent text-[10px] font-medium text-white"><Save size={12}/>保存项目</button></div></div>:<button onClick={()=>setCreatingProject(true)} className="m-2 flex h-9 items-center justify-center gap-2 rounded border border-border bg-white text-[10px] text-muted hover:bg-accent-subtle"><FolderPlus size={14}/>新建项目</button>}
        <nav className="flex-1 space-y-1 overflow-auto border-t border-border p-2">
          <button onClick={()=>{setSelectedProject(null);resetForm("");}} className={`flex h-9 w-full items-center gap-2 rounded border-0 px-2.5 text-left text-[11px] ${selectedProject===null?"bg-[#e6ebe2] text-foreground":"bg-transparent text-muted hover:bg-accent-subtle"}`}><Folder size={14}/><span className="flex-1 truncate">全部项目</span><b className="font-mono text-[9px] font-normal text-subtle">{prompts.length}</b></button>
          {projects.map(project=>editingProject?.id===project.id?<div key={project.id} className="rounded border border-[#b9c5b3] bg-white p-2"><input autoFocus value={editProjectName} onChange={e=>{setEditProjectName(e.target.value);setProjectError("");}} onKeyDown={e=>{if(e.key==="Enter")handleRenameProject();if(e.key==="Escape"){setEditingProject(null);setProjectError("");}}} className="h-8 w-full rounded border border-border px-2 text-[11px] outline-none focus:border-[#6b7f63]"/>{projectError&&<p className="mt-1 text-[9px] text-danger">{projectError}</p>}<div className="mt-1.5 grid grid-cols-2 gap-1"><button onClick={()=>{setEditingProject(null);setProjectError("");}} className="h-7 rounded border border-border bg-white text-[9px] text-muted">取消</button><button onClick={handleRenameProject} className="h-7 rounded border-0 bg-accent text-[9px] text-white">保存</button></div></div>:<div key={project.id} className={`group flex items-center rounded ${selectedProject===project.name?"bg-[#e6ebe2]":"hover:bg-accent-subtle"}`}><button onClick={()=>{setSelectedProject(project.name);resetForm(project.name);}} className="flex h-10 min-w-0 flex-1 items-center gap-2 border-0 bg-transparent px-2.5 text-left text-[11px] text-foreground"><Folder size={14} className="shrink-0"/><span className="flex-1 truncate">{project.name}</span><b className="font-mono text-[9px] font-normal text-subtle">{project.prompt_count}</b></button><button onClick={()=>{setEditingProject(project);setEditProjectName(project.name);setProjectError("");}} title="重命名项目" className="grid h-7 w-7 place-items-center rounded border-0 bg-transparent text-subtle opacity-0 hover:bg-white hover:text-foreground group-hover:opacity-100 focus:opacity-100"><Pencil size={12}/></button><button onClick={()=>handleDeleteProject(project)} title="删除项目" className="mr-1 grid h-7 w-7 place-items-center rounded border-0 bg-transparent text-subtle opacity-0 hover:bg-danger-bg hover:text-danger group-hover:opacity-100 focus:opacity-100"><Trash2 size={12}/></button></div>)}
        </nav>
      </>}
    </aside>
    <section className="relative min-w-0 flex-1 overflow-hidden">
      <header className="absolute left-0 right-0 top-0 z-20 flex h-[68px] items-center justify-between border-b border-border bg-[rgba(244,243,239,.92)] px-6 backdrop-blur-md">
        <div><div className="flex items-center gap-2"><span className="text-[10px] font-semibold uppercase text-subtle">{studioLabel}</span><span className="text-subtle">/</span><span className="text-[10px] font-semibold uppercase text-muted">{workspace}</span></div><h1 className="mt-1 text-sm font-semibold">{title}</h1></div>
        <div className="flex items-center gap-5 font-mono text-[9px] text-muted"><span><b className="mr-1.5 text-xs text-foreground">{projectCount}</b>项目</span><span><b className="mr-1.5 text-xs text-foreground">{visiblePromptCount}</b>节点</span><button onClick={()=>resetForm()} className="flex h-9 items-center gap-2 rounded border-0 bg-accent px-3.5 text-xs font-medium text-white hover:bg-accent-hover"><Plus size={15}/>新建</button></div>
      </header>
      {loading?<div className="grid h-full place-items-center text-xs text-muted"><span className="flex items-center gap-2"><LoaderCircle size={16} className="animate-spin"/>加载工作区</span></div>:
      <ReactFlow nodes={nodes} edges={edges} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onNodeClick={onNodeClick} onPaneClick={()=>resetForm()} nodeTypes={nodeTypes} fitView fitViewOptions={{padding:.22}} proOptions={{hideAttribution:true}} className="pt-[68px]">
        <Background variant={BackgroundVariant.Dots} gap={22} size={1} color="#c9cbc4"/><Controls position="bottom-left"/><MiniMap position="bottom-right" nodeColor="#6f7d69" pannable zoomable/>
      </ReactFlow>}
      {!loading&&visiblePromptCount===0&&<div className="pointer-events-none absolute inset-0 top-[68px] grid place-items-center"><div className="text-center"><GitBranchPlus size={24} className="mx-auto text-subtle"/><h2 className="mt-4 text-sm font-semibold">从第一个版本开始</h2><p className="mt-2 text-xs text-muted">在右侧填写提示词，版本关系会自动呈现在画布中。</p></div></div>}
    </section>

    <aside className="flex h-full w-[340px] shrink-0 flex-col border-l border-border bg-surface max-[1100px]:w-[310px] max-[760px]:absolute max-[760px]:inset-x-3 max-[760px]:bottom-3 max-[760px]:top-auto max-[760px]:z-50 max-[760px]:h-[62%] max-[760px]:w-auto max-[760px]:rounded-md max-[760px]:border max-[760px]:shadow-md">
      <div className="flex h-[68px] items-center justify-between border-b border-border px-5"><div><span className="text-[9px] font-semibold uppercase text-subtle">{selected?`Node #${selected.id}`:draftMode==="version"?"Version draft":draftMode==="iteration"?"Iteration draft":"New node"}</span><h2 className="mt-1 text-sm font-semibold">{selected?"编辑提示词":draftMode==="version"?"创建新版本":draftMode==="iteration"?"创建新迭代":"创建提示词"}</h2></div>{(selected||draftMode!=="new")&&<button onClick={draftMode!=="new"?discardDraft:()=>resetForm()} title={draftMode!=="new"?"放弃当前草稿":"关闭编辑"} className="grid h-8 w-8 place-items-center rounded border border-border bg-transparent text-muted hover:bg-accent-subtle"><X size={15}/></button>}</div>
      {draftMode!=="new"&&<div className="grid grid-cols-2 gap-2 border-b border-[#cbd4c6] bg-[#f1f5ee] p-3"><button onClick={discardDraft} className="flex h-10 items-center justify-center gap-2 rounded border border-border bg-white text-xs font-medium text-muted hover:bg-danger-bg hover:text-danger"><X size={14}/>放弃</button><button disabled={saving} onClick={handleCreate} className="flex h-10 items-center justify-center gap-2 rounded border-0 bg-accent text-xs font-medium text-white hover:bg-accent-hover disabled:opacity-60">{saving?<LoaderCircle size={14} className="animate-spin"/>:<Save size={14}/>} {saving?"保存中":draftMode==="version"?"保存新版本":"保存新迭代"}</button></div>}
      <div className="flex-1 space-y-6 overflow-auto p-5">
        <section><p className="mb-3 text-[9px] font-semibold uppercase text-subtle">01 / 基本信息</p><label className="block text-[11px] font-medium text-muted">所属项目</label><select className="mt-1.5 h-10 w-full rounded border border-border bg-[#fafaf8] px-3 text-xs outline-none transition focus:border-[#6b7f63] focus:bg-white focus:ring-2 focus:ring-[#e2e9de]" value={form.project_name} onChange={e=>setForm(f=>({...f,project_name:e.target.value}))}><option value="">选择项目</option>{projects.map(project=><option key={project.id} value={project.name}>{project.name}</option>)}</select><div className="mt-4 grid grid-cols-2 gap-3"><div><label className="block text-[11px] font-medium text-muted">版本</label><input type="number" min={1} className="mt-1.5 h-10 w-full rounded border border-border bg-[#fafaf8] px-3 font-mono text-xs outline-none focus:border-[#6b7f63]" value={form.version} onChange={e=>setForm(f=>({...f,version:Math.max(1,parseInt(e.target.value)||1)}))}/></div><div><label className="block text-[11px] font-medium text-muted">迭代</label><input type="number" min={1} className="mt-1.5 h-10 w-full rounded border border-border bg-[#fafaf8] px-3 font-mono text-xs outline-none focus:border-[#6b7f63]" value={form.iteration} onChange={e=>setForm(f=>({...f,iteration:Math.max(1,parseInt(e.target.value)||1)}))}/></div></div></section>
        <section><div className="mb-3 flex items-center justify-between"><p className="text-[9px] font-semibold uppercase text-subtle">02 / 提示词内容</p><div className="flex items-center gap-2"><span className="font-mono text-[9px] text-subtle">{form.content.length} chars</span>{form.content&&<button onClick={()=>setForm(f=>({...f,content:""}))} title="清空提示词" className="flex items-center gap-1 rounded border-0 bg-transparent px-1.5 py-1 text-[9px] text-muted hover:bg-danger-bg hover:text-danger"><Eraser size={12}/>清空</button>}</div></div><textarea className="h-[250px] w-full resize-none rounded border border-border bg-[#fafaf8] p-3 font-mono text-[11px] leading-6 outline-none transition focus:border-[#6b7f63] focus:bg-white focus:ring-2 focus:ring-[#e2e9de]" placeholder="描述主体、环境、光线、材质、构图与风格..." value={form.content} onChange={e=>setForm(f=>({...f,content:e.target.value}))}/></section>
        {referenceMode!=="none"&&<section><div className="mb-3 flex items-center justify-between"><p className="text-[9px] font-semibold uppercase text-subtle">03 / 参考图片</p><label className={`flex cursor-pointer items-center gap-1.5 rounded border border-border bg-white px-2 py-1 text-[9px] text-muted hover:bg-accent-subtle ${uploading?"pointer-events-none opacity-60":""}`}><input type="file" accept="image/*" multiple={referenceMode==="multi"} className="hidden" onChange={async e=>{const files=Array.from(e.target.files||[]);for(const file of files)await handleUpload(file,"input_images");e.target.value="";}}/>{uploading?<LoaderCircle size={12} className="animate-spin"/>:<ImagePlus size={12}/>}添加参考图</label></div>{form.input_images.length===0?<div className="grid h-20 place-items-center rounded border border-dashed border-border bg-[#fafaf8] text-center text-[10px] leading-5 text-subtle">{referenceMode==="single"?"添加一张参考图片":"添加多张参考图片用于组合"}</div>:<div className="grid grid-cols-2 gap-2">{form.input_images.map((url,index)=><div key={url} className="group relative aspect-square overflow-hidden rounded border border-border"><img src={url} alt={`参考图 ${index+1}`} className="h-full w-full object-cover"/><button onClick={()=>removeImage(url,index,"input_images")} title="移除参考图" className="absolute right-1 top-1 hidden h-7 w-7 place-items-center rounded border-0 bg-[rgba(25,28,23,.82)] text-white group-hover:grid"><Trash2 size={13}/></button></div>)}</div>}</section>}
        <section><div className="mb-3 flex items-center justify-between"><p className="text-[9px] font-semibold uppercase text-subtle">{referenceMode!=="none"?"04":"03"} / {outputLabel}</p><label className={`flex cursor-pointer items-center gap-1.5 rounded border border-border bg-white px-2 py-1 text-[9px] text-muted hover:bg-accent-subtle ${uploading?"pointer-events-none opacity-60":""}`}><input type="file" accept={assetKind==="media"?"image/*,video/mp4,video/webm,video/quicktime":"image/*"} className="hidden" onChange={e=>{const file=e.target.files?.[0];if(file)handleUpload(file);e.target.value="";}}/>{uploading?<LoaderCircle size={12} className="animate-spin"/>:<ImagePlus size={12}/>}上传产出</label></div>{form.output_images.length===0?<div className="grid h-20 place-items-center rounded border border-dashed border-border bg-[#fafaf8] text-[10px] text-subtle">暂无产出素材</div>:<div className="grid grid-cols-2 gap-2">{form.output_images.map((url,index)=><div key={`${url}-${index}`} className="group relative aspect-square overflow-hidden rounded border border-border bg-[#f2f2ef]">{isVideoUrl(url)?<video src={url} className="h-full w-full object-cover" muted/>:<img src={url} alt={`Output ${index+1}`} className="h-full w-full object-cover"/>}<div className="absolute inset-x-1 bottom-1 hidden items-center justify-center gap-1 rounded bg-[rgba(25,28,23,.84)] p-1 group-hover:flex group-focus-within:flex"><button onClick={()=>setPreviewImage(url)} title="查看素材" className="grid h-7 w-7 place-items-center rounded border-0 bg-transparent text-white hover:bg-white/15"><ZoomIn size={13}/></button><button onClick={async()=>{await navigator.clipboard.writeText(new URL(url,location.origin).href);setNotice({type:"success",text:"素材地址已复制"});}} title="复制地址" className="grid h-7 w-7 place-items-center rounded border-0 bg-transparent text-white hover:bg-white/15"><Copy size={13}/></button><a href={url} download title="下载素材" className="grid h-7 w-7 place-items-center rounded text-white hover:bg-white/15"><Download size={13}/></a><button onClick={()=>removeImage(url,index)} title="移除素材" className="grid h-7 w-7 place-items-center rounded border-0 bg-transparent text-white hover:bg-[#9c3f3b]"><Trash2 size={13}/></button></div></div>)}</div>}</section>
        {selected&&<div className="border-l-2 border-[#829479] bg-[#f5f7f3] px-3 py-2.5 text-[10px] text-muted"><div className="flex justify-between"><span>最后更新</span><span className="font-mono">{new Date(selected.updated_at).toLocaleString("zh-CN",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"})}</span></div></div>}
      </div>
      {draftMode==="new"&&<div className="border-t border-border bg-[#fafaf8] p-4">
        {selected&&<div className="mb-2 grid grid-cols-2 gap-2"><button onClick={handleNewVersion} className="flex h-9 items-center justify-center gap-2 rounded border border-border bg-white text-[11px] text-foreground hover:bg-accent-subtle"><CopyPlus size={14}/>新版本</button><button onClick={handleNewIteration} className="flex h-9 items-center justify-center gap-2 rounded border border-border bg-white text-[11px] text-foreground hover:bg-accent-subtle"><GitBranchPlus size={14}/>新迭代</button></div>}
        <div className="flex gap-2"><button disabled={saving} onClick={selected?handleUpdate:handleCreate} className="flex h-10 flex-1 items-center justify-center gap-2 rounded border-0 bg-accent text-xs font-medium text-white hover:bg-accent-hover disabled:opacity-60">{saving?<LoaderCircle size={15} className="animate-spin"/>:saved?<Check size={15}/>:selected?<Save size={15}/>:<Plus size={15}/>} {saving?"保存中":saved?"已保存":selected?"保存修改":"创建提示词"}</button>{selected&&<button onClick={handleDelete} title="删除提示词" className="grid h-10 w-10 place-items-center rounded border border-[#edd0cd] bg-white text-danger hover:bg-danger-bg"><Trash2 size={15}/></button>}</div>
      </div>}
    </aside>
    {previewImage&&<div className="fixed inset-0 z-[120] grid place-items-center bg-[rgba(19,21,18,.88)] p-8" onClick={()=>setPreviewImage(null)}><button onClick={()=>setPreviewImage(null)} title="关闭预览" className="absolute right-6 top-6 grid h-10 w-10 place-items-center rounded border border-white/20 bg-black/20 text-white"><X size={18}/></button>{isVideoUrl(previewImage)?<video src={previewImage} controls autoPlay className="max-h-full max-w-full" onClick={e=>e.stopPropagation()}/>:<img src={previewImage} alt="Output 素材预览" className="max-h-full max-w-full object-contain" onClick={e=>e.stopPropagation()}/>}<a href={previewImage} target="_blank" rel="noreferrer" className="absolute bottom-6 flex items-center gap-2 rounded bg-white px-3 py-2 text-xs text-foreground no-underline"><ExternalLink size={14}/>在新窗口打开</a></div>}
  </div>;
}

export default function TextToImagePage(){return <PromptFlowWorkspace/>;}
